#! /bin/sh
# chkconfig: 2345 88 12
# description: /etc/init.d/gsql_monitor, script to monitor GSQL processes

### BEGIN INIT INFO
# Provides:          gsql_monitor
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       script to start/stop GraphSQL monitor
### END INIT INFO

user='graphsql'
gmonitor=$(eval echo "~${user}/.gium/gsql_mon")
glogger=$(eval echo "~${user}/.gium/gsql_logger")

## check if /proc exists 
if ! grep -q '/proc' /etc/mtab
then
  echo "This system is not supported."
  exit 1
fi


startDaemon() 
{
  prog=$1
  if [ -x "$prog" ]
  then
    su - $user -c "$prog start"
  fi
}

stopDaemon() 
{
  prog=$1
  if [ -x "$prog" ]
  then
    su - $user -c "$prog stop"
  fi
}

loadConfig() 
{
  prog=$1
  if [ -x "$prog" ]
  then
    su - $user -c "$prog config reload"
  fi
}


case "$1" in
  start)
    startDaemon gmonitor
    startDaemon glogger >/dev/null 2>&1
    ;;
  stop)
    stopDaemon glogger >/dev/null 2>&1
    stopDaemon gmonitor
    ;;
  restart)
    stopDaemon glogger >/dev/null 2>&1
    stopDaemon gmonitor
    startDaemon gmonitor
    startDaemon glogger >/dev/null 2>&1
    ;;
  reload)
    echo "Reloading GSQL monitor configuration file"
    reloadConfig gmonitor
    stopDaemon glogger >/dev/null 2>&1
    startDaemon glogger >/dev/null 2>&1
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0
